### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by update-freak** [rainbowpigeon/sublime-text-4-patcher#1]
Hello developer,

I get the error message when executing the py-file:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\UpdateFreak\\Downloads'

The sublime_text_4_patcher.py and sublime_text.exe are in C:\Users\UpdateFreak\Downloads

System:
Windows 10 21H1 with Miniconda 3 (Python 3.9.5)

**Comment by ghost** [comment]
Hi!

What is your input to `sublime_file_path = input("Enter path to sublime_text.exe: ")`?
And you're running the script in the context of the Anaconda Prompt correct?

**Comment by update-freak** [comment]
Hi!

Found my mistake.
I entered C:\Users\UpdateFreak\Downloads instead off C:\Users\UpdateFreak\Downloads\sublime_text.exe
Thank you for your quick reply. Keep up the good work!

**Comment by SmartManoj** [comment]
#2
