### ISSUE TITLE
Build 4126 patcher not working

### ISSUE THREAD

**Issue by DeadLyBro** [rainbowpigeon/sublime-text-4-patcher#15]
OS: Windows 8.1 Pro 64-Bit. 

My console; 
```
C:\Program Files\Sublime Text 3>py -3 sublime_text_4_patcher.py
----------------------------------------------------------------
Sublime Text v4107-4138 Windows x64 Patcher by rainbowpigeon
----------------------------------------------------------------
Enter file path to sublime_text.exe: sublime_text.exe
[=] Processing ref for sig 48 8D 05 ? ? ? ? 48 8D 95 ? ? ? ? 48 89 02 48 8D 05 ? ? ? ? 48 89 42 08 48 8D 4D ? E8 ? ? ? ? B9...
[=] Found lea: \x48\x8d\x05\xe4\x48\x75\x00\x48\x8d\x95\x58\x02\x00\x00\x48\x89\x02\x48\x8d\x05\xd7\x48\x75\x00\x48\x89\x42\x08\x48\x8d\x4d\xb0\xe8\x28\x03\x00\x00\xb9
[=] Found relative address: 0x7548e4
[=] Determined actual offset: 0x759432
[+] Sublime Text Version 4126 detected
[=] Processing ref for sig 4C 8D 4D ? E8 ? ? ? ? ? 8B ? ? ? ? ? 85 C0...
[=] Found call: \x4c\x8d\x4d\x54\xe8\x0b\xe2\xff\xff\x49\x8b\x8e\x68\x02\x00\x00\x85\xc0
[=] Found relative address: 0xffffe20b
[=] Determined actual offset: 0xa7214
[+] Applying all patches...
[=] Offset 0x711a  : patching \xe8\xe1\x36\x20\x00 with \x90\x90\x90\x90\x90
[=] Offset 0x7133  : patching \xe8\xc8\x36\x20\x00 with \x90\x90\x90\x90\x90
[=] Offset 0xa7214 : patching \x55\x41\x57\x41 with \x48\x31\xc0\xc3
[=] Offset 0xa8d53 : patching \x55\x56\x57\x48\x83\xec\x30 with \x48\x31\xc0\x48\xff\xc0\xc3
[=] Offset 0xa6e0f : patching \x55\x56\x57\x48 with \x48\x31\xc0\xc3
[=] Offset 0x400   : patching \x41 with \xc3
[+] All patches applied!
[+] Backing up original file at sublime_text.exe.bak
[+] Patched file written at sublime_text.exe
Enjoy! :)
----------------------------------------------------------------
Report any issues at github.com/rainbowpigeon/sublime-text-4-patcher/issues!
----------------------------------------------------------------
```
Ps: I installed requirements. Not working.

![Screenshot](https://user-images.githubusercontent.com/31214077/199974055-17da3e6a-7aec-41d3-824d-c3d9c8c9b028.png)

Also i check py code backing up exe file (exe.bak)

**Comment by Keith94** [comment]
Not related to this patcher, but if you're familiar with hex editing you can try [this solution for build 4126](https://www.nairatag.com/general/crack-sublime-text-4-easily/) (I used [HxD](https://mh-nexus.de/en/hxd/) for editing).

**Comment by DeadLyBro** [comment]
> Not related to this patcher, but if you're familiar with hex editing you can try [this solution for build 4126](https://www.nairatag.com/general/crack-sublime-text-4-easily/) (I used [HxD](https://mh-nexus.de/en/hxd/) for editing).

Thanks i'll try this program.

**Comment by DeadLyBro** [comment]
> Not related to this patcher, but if you're familiar with hex editing you can try [this solution for build 4126](https://www.nairatag.com/general/crack-sublime-text-4-easily/) (I used [HxD](https://mh-nexus.de/en/hxd/) for editing).

This program worked for me, thank you @Keith94 .

**Comment by ghost** [comment]
I've downloaded a fresh build of 4126, ran my patcher script, and I can confirm that the script works and produces the same console output as yours.

I think what you're missing is this: after the script is run, you need to go to Help > Enter License, type in any text, and click Use License. After this it should no longer show Unregistered.

Does this resolve your issue? @DeadLyBro

**Comment by DeadLyBro** [comment]
> I've downloaded a fresh build of 4126, ran my patcher script, and I can confirm that the script works and produces the same console output as yours.
> 
> I think what you're missing is this: after the script is run, you need to go to Help > Enter License, type in any text, and click Use License. After this it should no longer show Unregistered.
> 
> Does this resolve your issue? @DeadLyBro

Dude i'm already do with another program and its registered. 

Someone else will try and send the results?

**Comment by ghost** [comment]
Oh ok no worries then. If you still want to try it without affecting the already-registered Sublime Text installed in your system, you can try it with the portable build: https://download.sublimetext.com/sublime_text_build_4126_x64.zip

**Comment by DeadLyBro** [comment]
> Oh ok no worries then. If you still want to try it without affecting the already-registered Sublime Text installed in your system, you can try it with the portable build: https://download.sublimetext.com/sublime_text_build_4126_x64.zip

Also  you should add " `Help > Enter License` write something and click `Use License`. "  to readme.md's bottom.

**Comment by ghost** [comment]
Good point! I'll also probably add it into the script's output as an additional reminder.

**Comment by DeadLyBro** [comment]
Sublime Text updated 4142 and this patcher not working for now...

**Comment by ghost** [comment]
> Sublime Text updated 4142 and this patcher not working for now...

Looking into it now 👍

**Comment by DeadLyBro** [comment]
> > Sublime Text updated 4142 and this patcher not working for now...
> 
> Looking into it now +1

I patched already with hex editor... So i can't try :skull: 
With [this](https://github.com/rainbowpigeon/sublime-text-4-patcher/issues/15#issuecomment-1304007500) method.

**Comment by ghost** [comment]
> I patched already with hex editor... So i can't try 💀

That's fine, I can test it myself. Thanks for letting me know there's a new stable version released.

**Comment by DeadLyBro** [comment]
> That's fine, I can test it myself. Thanks for letting me know there's a new stable version released.

You're welcome.
