### ISSUE TITLE
No module named 'prefile'

### ISSUE THREAD

**Issue by okay-bullo** [rainbowpigeon/sublime-text-4-patcher#18]
I got the following error

Traceback (most recent call last):
  File "sublime_text_4_patcher.py", line 8, in <module>
    import prefile
ModuleNotFoundError: No module named 'prefile'

Although I followed all the instructions and it even says when I try to reinstall prefile

Requirement already satisfied: pefile in c:\users\no name\appdata\local\programs\python\python37\lib\site-packages (2021.5.24)
Requirement already satisfied: future in c:\users\no name\appdata\local\programs\python\python37\lib\site-packages (from pefile) (0.18.2)

Is there a solution?

**Comment by rainbowpigeon** [comment]
> Traceback (most recent call last): 
> File "sublime_text_4_patcher.py", line 8, in 
> import prefile 
> ModuleNotFoundError: No module named 'prefile'

Line 8 in `sublime_text_4_patcher.py` should be `import pefile` not `import prefile`.
