### ISSUE TITLE
Broken signatures in latest dev build 4172

### ISSUE THREAD

**Issue by godrider** [rainbowpigeon/sublime-text-4-patcher#21]
Dev build 4172 just got released and all the signatures except for `invalidate1_0x6` and `invalidate2_0x6` are broken.

**Comment by godrider** [comment]
I have created [new signatures](https://github.com/godrider/sublime-text-4-patcher/commit/a07b5bf06713893cd7a8e37dfb9e9b93876c9ba2) for this build. I dropped the support for older builds in my fork. It's just too much work.

**Comment by rainbowpigeon** [comment]
Fixed with https://github.com/rainbowpigeon/sublime-text-4-patcher/commit/eca6c4846f8a35ccf71c190dcc627a8a062354cb. Older builds should still be supported.
