### ISSUE TITLE
Build 4189 (license upgrade required)

### ISSUE THREAD

**Issue by Keith94** [rainbowpigeon/sublime-text-4-patcher#25]
![sublime_text_XRyijJv1OR](https://github.com/user-attachments/assets/e3832bf3-138d-46a8-904b-c8500a47eae0)

Anybody know if the patch needs adjusting for the latest version?

**Comment by rainbowpigeon** [comment]
You can update and re-patch the new executable with the latest sublime-text-4-patcher.

**Comment by Keith94** [comment]
Sounds good, thank you for the quick response
