### ISSUE TITLE
v4121 out

### ISSUE THREAD

**Issue by SmartManoj** [rainbowpigeon/sublime-text-4-patcher#6]

**Comment by ghost** [comment]
Done. Test it out and let me know if there's anything wrong!

**Comment by keatit71** [comment]
It works fine, although before i tried just changing a couple values with a hex editor to disable key and license checking. Is there any difference between these methods except when doing the hex windows smart screen pops up

**Comment by ghost** [comment]
At its core, there is no difference. This script also changes hex values (probably the same ones that you are changing). 
What differs on the outside is that the script uses byte patterns with wildcards to determine the location of these hex values to edit, as compared to using specific file offsets that will more likely vary across release versions.
Oh and yeah, I also added automatic version detection and patching based on your version/release channel. Also achieved using byte patterns.

I hope that provides sufficient clarity.
